buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.1.0'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
        maven { url 'https://oss.sonatype.org/content/repositories/releases/' }
    }
}

ext {
    appName        = "TowerDefense"
    gdxVersion     = '1.12.1'
    roboVMVersion  = '2.3.21'
    box2DLightsVersion = '1.5'
    ashleyVersion  = '1.7.4'
    aiVersion      = '1.8.2'
    gdxControllersVersion = '2.2.1'
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
